
-- Tabela para armazenar as músicas do dataset
CREATE TABLE public.songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INT NOT NULL,
    rank INT,
    artist TEXT,
    title TEXT NOT NULL,
    lyrics TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security (boa prática)
ALTER TABLE public.songs ENABLE ROW LEVEL SECURITY;

-- Política para permitir acesso público de leitura à tabela de músicas
CREATE POLICY "Allow public read access to songs"
ON public.songs
FOR SELECT
USING (true);

-- Tabela para armazenar os rótulos manuais feitos pela equipe
CREATE TABLE public.manual_labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    song_id BIGINT NOT NULL REFERENCES public.songs(id) ON DELETE CASCADE,
    theme TEXT NOT NULL,
    score REAL NOT NULL CHECK (score >= 0 AND score <= 1),
    justification TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security
ALTER TABLE public.manual_labels ENABLE ROW LEVEL SECURITY;

-- Política para permitir acesso público total (leitura, escrita, etc.) à tabela de rótulos.
-- Isso simplifica o desenvolvimento para este projeto acadêmico.
CREATE POLICY "Allow public access to manual labels"
ON public.manual_labels
FOR ALL
USING (true)
WITH CHECK (true);

